[package]
name = "minimal-yaml"
version = "0.1.0"
authors = ["Nathan Whitaker <nathan.whitaker01@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
serde = {version = "1.0.104", features = ['derive'], optional = true}

[dev-dependencies]
paste = "0.1.6"